apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgresql-storage
provisioner: microk8s.io/hostpath
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
